# Portul pe care va rula serverul de backend (frontend-ul e pe 3000)
server.port=8080

# Conexiunea la PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nouatacasa
spring.datasource.username=postgres
spring.datasource.password=Bogdan.1972lrvxi
spring.datasource.driver-class-name=org.postgresql.Driver

# Configur?ri Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pentru faza de MVP, l?s?m Hibernate s? creeze ?i s? actualizeze tabelele automat
spring.jpa.hibernate.ddl-auto=update
